version: '3.7'

services:

  node:
    container_name: nodeapp
    image: nodeapp
    build:
      context: ./                   # the buildfile is in this dir
      dockerfile: node.dockerfile  #name of dockerfile
      args:
        buildversion: 1           # define the value and pass it into build and rest in dockerfile
    environment:                  # DC pass env. variables at runtime in Yml
      - NODE_ENV=production
      - PORT=3000
      - build=1
    ports:
      - "3000:3000"
    networks:
      - nodeapp-network
    volumes:
      - ./logs:/var/www/logs
    depends_on: 
      - mongodb
      
  mongodb:
    container_name: mongodb
    image: mongo
    networks:
      - nodeapp-network

networks:
  nodeapp-network:
    driver: bridge